default: &default
  adapter: postgresql
  encoding: <%= ENV.fetch("PG_ENCODE", "unicode") %>
  max_connections: <%= ENV.fetch("RAILS_MAX_THREADS", 5 ) %>
  timeout: <%= ENV.fetch("PG_TIMEOUT", 5000) %>
  username: <%= ENV.fetch("PG_USER", "postgres") %>
  password: <%= ENV.fetch("PG_PASSWORD", "postgres") %>
  host: <%= ENV.fetch("PG_HOST", "localhost") %>
  port: <%= ENV.fetch("PG_PORT", "5432") %>

development:
  <<: *default
  database: <%= ENV.fetch("PG_DATABASE_DEV", "portfolio_development") %>

test:
  <<: *default
  database: <%= ENV.fetch("PG_DATABASE_TEST", "portfolio_test") %>

production:
  primary:
    <<: *default
    database: <%= ENV.fetch("PG_DATABASE_PRO", "portfolio_production") %>
  cache:
    <<: *default
    database: <%= ENV.fetch("PG_DATABASE_CACHE", "portfolio_cache") %>
    migrations_paths: db/cache_migrate
  queue:
    <<: *default
    database: <%= ENV.fetch("PG_DATABASE_QUEUE", "portfolio_queue") %>
    migrations_paths: db/queue_migrate
  cable:
    <<: *default
    database: <%= ENV.fetch("PG_DATABASE_CABLE", "portfolio_cable") %>
    migrations_paths: db/cable_migrate
