name: 🧪 RSpec Test (rspec)

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      RAILS_ENV: test

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

#      - name: Install ImageMagick
#        run: sudo apt-get update && sudo apt-get install -y imagemagick

      - name: Set up database
        run: |
          bin/rails db:prepare

      - name: Run RSpec
        run: bundle exec rspec

      - name: Upload coverage report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage

#      - name: Commit coverage badge
#        run: |
#          git config --global user.name github-actions
#          git config --global user.email github-actions@github.com
#          git add coverage/badge.svg
#          git commit -m "Update coverage badge" || echo "No changes"
#          git push
