name: 🧹 HAML (haml-lint)

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  rubocop:
    runs-on: ubuntu-latest

    env:
      RUBOCOP_CACHE_ROOT: tmp/rubocop

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
          bundler-cache: true

      - name: Run HAML Lint
        run: bundle exec haml-lint .
